-- MySQL Script generated by MySQL Workbench
-- 06/06/17 13:09:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema arduinodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema arduinodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `arduinodb` DEFAULT CHARACTER SET utf8 ;
USE `arduinodb` ;

-- -----------------------------------------------------
-- Table `arduinodb`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arduinodb`.`account` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `arduinodb`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arduinodb`.`post` (
  `idpost` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ownerid` INT(10) UNSIGNED NOT NULL,
  `detail` VARCHAR(500) NOT NULL,
  `bounty` DOUBLE UNSIGNED NOT NULL,
  `topic` VARCHAR(200) NOT NULL,
  `target` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`idpost`),
  UNIQUE INDEX `idpost_UNIQUE` (`idpost` ASC),
  INDEX `id_idx` (`ownerid` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`ownerid`)
    REFERENCES `arduinodb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `arduinodb`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `arduinodb`.`comment` (
  `commentID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `postID` INT(10) UNSIGNED NOT NULL,
  `detail` VARCHAR(500) NOT NULL,
  `userID` INT(10) UNSIGNED NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`commentID`),
  UNIQUE INDEX `commentID_UNIQUE` (`commentID` ASC),
  INDEX `id_idx` (`userID` ASC),
  INDEX `idpost_idx` (`postID` ASC),
  CONSTRAINT `postID`
    FOREIGN KEY (`postID`)
    REFERENCES `arduinodb`.`post` (`idpost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userID`
    FOREIGN KEY (`userID`)
    REFERENCES `arduinodb`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
