/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model.dao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import static java.sql.Statement.RETURN_GENERATED_KEYS;

/**
 *
 * @author chawanvtp
 */
public class AddPostDao {
    
    private String driver = "com.mysql.jdbc.Driver";
    private String url = "jdbc:mysql://localhost:3306/arduinodb?zeroDateTimeBehavior=convertToNull";
    private String user = "root";
    private String pass = "123455";
    private Connection connect = null;
    
    public AddPostDao() throws ClassNotFoundException{
        try {
            Class.forName(driver);
            connect = DriverManager.getConnection(url,user,pass);
    } catch (Exception e){
        e.printStackTrace();
    }
    }
    
    public void close() {
 
        try {
 
            if(connect != null) {
 
            connect.close();
 
            }
 
            } catch (Exception e) {
 
                e.printStackTrace();
 
             }
 
    }
    
    public void Add(int ownerid,String detail, double bounty, String topic, String target){
        String sql = "INSERT into post (ownerid,detail,bounty,topic,target) VALUES ('"+ownerid+"','"+detail+"','"+bounty+"','"+topic+"','"+target+"')";
        try {
            PreparedStatement ps = connect.prepareStatement(sql, PreparedStatement.RETURN_GENERATED_KEYS);
            
            ps.executeUpdate();
            ResultSet tableKeys = ps.getGeneratedKeys();
            tableKeys.next();
            int autoGeneratedID = tableKeys.getInt(1);
            connect.close();
        } catch (Exception e){
             System.out.println("FAILED at FindAll()");
            e.printStackTrace();
        }
               
    }
    
}
